/**
 * Search namespaces
 */
export const SEARCH_RESULT_ADD_RECORD = 'SEARCH_RESULT_ADD_RECORD';
export const SEARCH_RESULT_CLAIM_PUBLICATION = 'SEARCH_RESULT_CLAIM_PUBLICATION';

/**
 * Search sources
 */
export const SOURCE_WOS = 'wos';
export const SOURCE_CROSSREF = 'crossref';
export const SOURCE_SCOPUS = 'scopus';
export const SOURCE_PUBMED = 'pubmed';

/**
 * List of valid external sources
 *
 * @type {[*]}
 */
export const validExternalSources = [
    SOURCE_CROSSREF,
    SOURCE_PUBMED,
    SOURCE_SCOPUS,
    SOURCE_WOS
];

/**
 * Search action types
 */
export const SEARCH_INITIATED = 'SEARCH_INITIATED';

export const SEARCH_LOADING = 'SEARCH_LOADING';
export const WOS_SEARCH_LOADING = 'WOS_SEARCH_LOADING';
export const SCOPUS_SEARCH_LOADING = 'SCOPUS_SEARCH_LOADING';
export const CROSSREF_SEARCH_LOADING = 'CROSSREF_SEARCH_LOADING';
export const PUBMED_SEARCH_LOADING = 'PUBMED_SEARCH_LOADING';
export const INTERNAL_SEARCH_LOADING = 'INTERNAL_SEARCH_LOADING';

export const SEARCH_COMPLETED = 'SEARCH_COMPLETED';
export const WOS_SEARCH_COMPLETED = 'WOS_SEARCH_COMPLETED';
export const SCOPUS_SEARCH_COMPLETED = 'SCOPUS_SEARCH_COMPLETED';
export const CROSSREF_SEARCH_COMPLETED = 'CROSSREF_SEARCH_COMPLETED';
export const PUBMED_SEARCH_COMPLETED = 'PUBMED_SEARCH_COMPLETED';
export const INTERNAL_SEARCH_COMPLETED = 'INTERNAL_SEARCH_COMPLETED';

export const SEARCH_FAILED = 'SEARCH_FAILED';
export const WOS_SEARCH_FAILED = 'WOS_SEARCH_FAILED';
export const SCOPUS_SEARCH_FAILED = 'SCOPUS_SEARCH_FAILED';
export const CROSSREF_SEARCH_FAILED = 'CROSSREF_SEARCH_FAILED';
export const PUBMED_SEARCH_FAILED = 'PUBMED_SEARCH_FAILED';
export const INTERNAL_SEARCH_FAILED = 'INTERNAL_SEARCH_FAILED';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

