/**
 * Created by uqvasai on 17/07/2017.
 */
export const SEARCH_INITIATED = 'SEARCH_INITIATED';

export const SEARCH_LOADING = 'SEARCH_LOADING';
export const WOS_SEARCH_LOADING = 'WOS_SEARCH_LOADING';
export const SCOPUS_SEARCH_LOADING = 'SCOPUS_SEARCH_LOADING';
export const CROSSREF_SEARCH_LOADING = 'CROSSREF_SEARCH_LOADING';
export const PUBMED_SEARCH_LOADING = 'PUBMED_SEARCH_LOADING';
export const INTERNAL_SEARCH_LOADING = 'INTERNAL_SEARCH_LOADING';

export const SEARCH_COMPLETED = 'SEARCH_COMPLETED';
export const WOS_SEARCH_COMPLETED = 'WOS_SEARCH_COMPLETED';
export const SCOPUS_SEARCH_COMPLETED = 'SCOPUS_SEARCH_COMPLETED';
export const CROSSREF_SEARCH_COMPLETED = 'CROSSREF_SEARCH_COMPLETED';
export const PUBMED_SEARCH_COMPLETED = 'PUBMED_SEARCH_COMPLETED';
export const INTERNAL_SEARCH_COMPLETED = 'INTERNAL_SEARCH_COMPLETED';

export const SEARCH_FAILED = 'SEARCH_FAILED';
export const WOS_SEARCH_FAILED = 'WOS_SEARCH_FAILED';
export const SCOPUS_SEARCH_FAILED = 'SCOPUS_SEARCH_FAILED';
export const CROSSREF_SEARCH_FAILED = 'CROSSREF_SEARCH_FAILED';
export const PUBMED_SEARCH_FAILED = 'PUBMED_SEARCH_FAILED';
export const INTERNAL_SEARCH_FAILED = 'INTERNAL_SEARCH_FAILED';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
